### ISSUE TITLE
The sort command is case sensitive

### ISSUE THREAD

**Issue by jonatanlehtinen** [CS2103AUG2017-T15-B3/main#108]
![image](https://user-images.githubusercontent.com/18460598/32362653-0569385e-c0a6-11e7-82db-cdc9ac1f0679.png)

As shown in the picture, the sort command is case sensitive. This means that the contact "john doe" is listed as the last person after running the sort command because the name starts with a lower case letter.

**Comment by DarrenCzen** [comment]
Thanks for your recommendation, I just implemented something related to this cause of your recommendation! Thanks a lot!
