### ISSUE TITLE
User feedback inaccurate

### ISSUE THREAD

**Issue by danielbrzn** [CS2103AUG2017-T15-B3/main#111]
![image](https://user-images.githubusercontent.com/251231/32362980-e5a3a37c-c0a7-11e7-9acf-15f501b6af31.png)

Editing a birthday of a person and having the birthday being invalid shows the user a feedback that concerns person's name validity even though person name was not being edited

**Comment by archthegit** [comment]
Thanks for the feedback! The myth's book has fixed it now!
