### ISSUE TITLE
Inaccurate information in Help

### ISSUE THREAD

**Issue by nbriannl** [CS2103AUG2017-T15-B3/main#114]
Help says

> It is encouraged to have https://www. and a domain name like .com or .net in the inputted website or it will result in website input error.

It is actually **compulsory** to have https://www. else the website url will not be accepted.

![image](https://user-images.githubusercontent.com/27397021/32363387-17745520-c0aa-11e7-8ba3-421a5797346b.png)

**Comment by archthegit** [comment]
Nice catch! The Myth's Book is working on it right now

**Comment by DarrenCzen** [comment]
Resolved! Thanks for recommendation.
