### ISSUE TITLE
Person's tags do not update after edit

### ISSUE THREAD

**Issue by danielbrzn** [CS2103AUG2017-T15-B3/main#116]
![image](https://user-images.githubusercontent.com/251231/32363537-cee89a0e-c0aa-11e7-87e2-24d78beb769f.png)

Editing a person's tags does not update the Person details view with the new tags.
Using select index also does not update the person view.
Have to switch to another person and then back to have it update.

E.G.

edit 1 t/afaw t/awfff (desc. not updated)
select 1 (desc. not updated)
select 2 (desc updated to other person)
select 1 (desc finally updated)

**Comment by archthegit** [comment]
Good find! We're working on it now
