### ISSUE TITLE
code quality comments for itsdickson

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B3/main#148]
![image](https://user-images.githubusercontent.com/1023494/32653887-47a920aa-c644-11e7-87c8-e1424940eb0e.png)
- header comment not following the convention we specify

@itsdickson FYA

**Comment by itsdickson** [comment]
Noted with thanks! Will change. Thank you sir!

**Comment by itsdickson** [comment]
![image](https://user-images.githubusercontent.com/30717938/32708104-25dcc492-c863-11e7-861a-8736326f2e2c.png)

Sir, I followed the comment of ShowHelpRequestEvent, since it was for a similar use. Would that be ok or do I change it?

**Comment by okkhoy** [comment]
Would suggest you to change it.

**Comment by itsdickson** [comment]
if that's the case, should i change the ShowHelpRequestEvent as well?

**Comment by okkhoy** [comment]
"you can, but not expected to, fix existing problems"

**Comment by itsdickson** [comment]
i have fixed it, thank you sir !
