### ISSUE TITLE
code quality comments for archthegit

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B3/main#149]
![image](https://user-images.githubusercontent.com/1023494/32653956-86eb4c48-c644-11e7-8c91-d2141aa39a8d.png)
- header comments don't follow the convention we specify

![image](https://user-images.githubusercontent.com/1023494/32653974-9a8e333c-c644-11e7-8197-d2e183fe9ba1.png)
- Woah!!

@archthegit FYA

**Comment by archthegit** [comment]
Hi Akshay, noted. About the regex, it is needed to validate most dates. Is it okay? Or should I try to reduce it?

**Comment by okkhoy** [comment]
i just exclaimed! you may or may not want to do anything abt it :stuck_out_tongue_winking_eye:
