### ISSUE TITLE
Everything on track to submit?

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B3/main#166]
Everything on track to submit? Remember to read submission instructions carefully and plan to finish submissions at least few hours before the deadline. All the best :+1:

**Comment by archthegit** [comment]
Hi Akshay,
Everything is somewhat on track.

**Comment by itsdickson** [comment]
Thank you sir, for your concern!

**Comment by chernghann** [comment]
Thanks sir

**Comment by DarrenCzen** [comment]
Yes sir we are almost done. Compiling files for submission now. Thank you for your concern sir.
